# Generated by Django 5.0.4 on 2024-04-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_installment'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='interest',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
    ]
