# Generated by Django 5.0.4 on 2024-04-14 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_loan_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='interest',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
