# Generated by Django 5.0.4 on 2024-04-14 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0005_alter_loan_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installment',
            name='collector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loan.collector'),
        ),
    ]
