# Generated by Django 5.0.4 on 2024-04-14 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0006_alter_installment_collector'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='month',
            field=models.CharField(default='january', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='installment',
            name='year',
            field=models.PositiveIntegerField(default=2024),
            preserve_default=False,
        ),
    ]
