# Generated by Django 5.0.4 on 2024-04-14 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0007_installment_month_installment_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='amount_to_deliver',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='amount_with_interest',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='fees',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='installment',
            name='month',
            field=models.CharField(editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='installment',
            name='year',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='loan',
            name='collected',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
    ]
