# Generated by Django 5.0.4 on 2024-04-14 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0008_loan_amount_to_deliver_loan_amount_with_interest_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='installment',
            options={'ordering': ('date',)},
        ),
        migrations.AddField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed')], default='Active', max_length=6),
        ),
    ]
