# Generated by Django 5.0.4 on 2024-04-16 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0009_alter_installment_options_loan_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collector',
            options={'ordering': ('name',), 'verbose_name': 'محصل', 'verbose_name_plural': 'محصلون'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ('name',), 'verbose_name': 'عميل', 'verbose_name_plural': 'عملاء'},
        ),
        migrations.AlterModelOptions(
            name='installment',
            options={'ordering': ('date',), 'verbose_name': 'قسط', 'verbose_name_plural': 'أقساط'},
        ),
        migrations.AlterModelOptions(
            name='loan',
            options={'verbose_name': 'قرض', 'verbose_name_plural': 'قروض'},
        ),
        migrations.AlterModelOptions(
            name='shareholder',
            options={'ordering': ('name',), 'verbose_name': 'شريك', 'verbose_name_plural': 'شركاء'},
        ),
        migrations.AlterField(
            model_name='collector',
            name='name',
            field=models.CharField(max_length=100, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المدفوع'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='collector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loan.collector', verbose_name='المحصل'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='date',
            field=models.DateField(verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_installment', to='loan.loan', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='installment',
            name='month',
            field=models.CharField(editable=False, max_length=20, verbose_name='الشهر'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='تم الدفع'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='year',
            field=models.PositiveIntegerField(editable=False, verbose_name='السنة'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='القيمة'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='amount_to_deliver',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='المبلغ المسلم'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='amount_with_interest',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='القيمة بالفائدة'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='collected',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10, verbose_name='المبلغ المحصل'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='collector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.collector', verbose_name='المحصل'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_customer', to='loan.customer', verbose_name='العميل'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='duration',
            field=models.PositiveIntegerField(verbose_name='المدة'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='fees',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10, verbose_name='الرسوم الإدارية'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='guarantor1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_guarantor1', to='loan.customer', verbose_name='الضامن الأول'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='guarantor2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_guarantor2', to='loan.customer', verbose_name='الضامن الثاني'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الفائدة'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='shareholder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.shareholder', verbose_name='الشريك'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='start_date',
            field=models.DateField(verbose_name='تاريخ البدء'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('Active', 'نشط'), ('Closed', 'مغلق')], default='Active', max_length=6, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='shareholder',
            name='name',
            field=models.CharField(max_length=100, verbose_name='الاسم'),
        ),
    ]
