# Generated by Django 5.0.4 on 2024-05-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0010_alter_collector_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10, verbose_name='العمولة'),
        ),
    ]
