# Generated by Django 5.0.4 on 2024-05-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0011_loan_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='day',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
