# Generated by Django 5.0.4 on 2024-05-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0012_installment_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10, verbose_name='العمولة'),
        ),
    ]
